### ISSUE TITLE
Service Binding 2

### ISSUE THREAD

**Issue by plorenz** [netfoundry/ziti-fabric#38]
Currently we try to derive binding based on address when creating services. Should we do that dynamically when being dialed? 
If not, we need to enforce service binding so that edge cannot bind a non-edge service.

**Comment by michaelquigley** [comment]
I'm not sure I'm following you. The binding is the binding. The address is the address. For plain fabric services, the binding is resolved and passed the address when dialing the termination of the service. The address needs to be in a format understood by the xgress component named by the binding.

The fabric should not understand anything about edge services. This sounds like something that should be layered on top of the fabric within the edge itself?

**Comment by plorenz** [comment]
This will be resolved by the work to extract terminators from services. See https://github.com/netfoundry/ziti-fabric/wiki/Pluggable-Service-Terminators
