### ISSUE TITLE
Pluggable Service Terminator Strategies (with High Availability Implementations)

### ISSUE THREAD

**Issue by plorenz** [netfoundry/ziti-fabric#48]
Currently services have the following attributes

* name
* binding
* egressRouter
* endpointAddress

To be able to support failover and HA capable services, we need to be able to support services with multiple endpoints. To support all of the use cases, we could split out the endpoint information into a separate structure.

Service would just retain

* name

There would be a new structure, name TBD (endpoint, terminator, egressPoint), which would have the following attributes

* id and/or name?
* priority
* binding
* egressRouter
* endpointAddress

When a new session is established the controller would pick an endpoint from all endpoints which had the highest priority. 

For SDK applications which are binding, these entries would get created/removed dynamically. The binding would allow setting the priority. The priority could also be specified as -1, which would set the priority to one lower than the currently lowest priority. 

So to model different scenarios - 

HA - many endpoints with the same priority
Main/backups - N endpoints with priority 0, 1, etc...
Rolling failover - N endpoints, each one grabs the next lowest priority as they bind, so that we don't fail back when servers come back up

We could also store these entries associated to router and then dynamically add/remove them to/from the services as the router goes online/offline

**Comment by plorenz** [comment]
Note: this will likely resolve #38

**Comment by plorenz** [comment]
Prompted by discussions with @michaelquigley, going to examine this from the other perspective. The above looks at a solution and examines which use cases we could solve with it. Let's explicitly list which use cases we want to support and see what we need to support them.

**Proposed Requirements**

  1. Ability to support multiple strategies, including pluggable strategies. This implies that we have an 
API for strategies and a way to register them.
  1. Bundled strategies should include:
      1. some form of horizontal scale, where multiple endpoints can bind and the controller will load balance sessions across those endpoints using some algorithm
      1. some form of active/passive, where multiple endpoints can bind, but the controller will use a single endpoint for all sessions until that endpoint fails, at which point the controller will failover to another endpoint.
  1. Some way to provide per endpoint context, which can feed into endpoint selection strategies. Some examples of the kinds of context an endpoint might want to provide are:
      1. Priority - This would allow a strategy to rank endpoints and select a subset of endpoints to load balance sessions across.
      1. Weight - This would allow a strategy to better to decide how to load balance across endpoints. Endpoints with a lower weight would receive a lower percentage of sessions

Strategies could also use things like bind time and drive traffic to the endpoint which has been around the longest. 

**Proposal**
  1. Add EndpointStrategy API to fabric and allow registration of endpoint strategies  
  1. Add endpointStrategy field to service, so endpoint strategies can be configured per-service
  1. Add endpoint entity to fabric model with the following fields
      1. id - string
      1. binding - string
      1. egressRouter - string (must be existing router id)
      1. endpointAddress - string
      1. createdAt - datetime
      1. strategyOptions - map[string]interface{}
     
The strategyOptions field could be a map of strategy name -> single value or map of values. 

**API**
```
type TerminatingEndpoint struct {
    id string
    binding string
    egressRouter string
    endpointAddress string
    createAt time.Time
    strategyOptions map[string]
}

type EndpointStrategy interface {
    GetEndpoint(service *Service, clientId string, endpoints[]*TerminatingEndpoint) *TerminatingEndpoint
}
```

*Example One*
Let's suppose we have a webservice we want to provide horizontally scaled access, where endpoints are load balanced using random selection.

* service 
  * name: my-web-service
  * endpointStrategy: hs-random
* binding 1
  * id: <uuid>
  * binding: edge
  * egressRouter: <uuid>
  * endpointAddress: hosted:<uuid>
  * createdAt: Wed 19 Feb 2020 02:08:02 PM EST
  * strategyOptions: nil
* binding 2
  * id: <uuid>
  * binding: edge
  * egressRouter: <uuid>
  * endpointAddress: hosted:<uuid>
  * createdAt: Wed 19 Feb 2020 02:08:02 PM EST
  * strategyOptions: nil

Here the strategy doesn't require any contextual data. It would probably be implemented something like:

```
type HSRandomStrategy struct {}

func (HSRandomStrategy)  GetEndpoint(_ *Service, _ string, endpoints[]*TerminatingEndpoint) *TerminatingEndpoint {
   idx := rand.Intn(len(endpoints))
   return endpoints[idx]
}
```

*Example Two*
Let's suppose we have a database service where we have a primary and backup. We want to the primary if available, otherwise use the backup. We could represent this with priorities, where the primary gets priority 0 and the backup gets priority 1.

* service 
  * name: my-db
  * endpointStrategy: ha-priority
* binding 1
  * id: <uuid>
  * binding: edge
  * egressRouter: <uuid>
  * endpointAddress: hosted:<uuid>
  * createdAt: Wed 19 Feb 2020 02:08:02 PM EST
  * strategyOptions: map[string]interface{} { "ha-priority" : 0 }
* binding 2
  * id: <uuid>
  * binding: edge
  * egressRouter: <uuid>
  * endpointAddress: hosted:<uuid>
  * createdAt: Wed 19 Feb 2020 02:08:02 PM EST
  * strategyOptions: map[string]interface{} { "ha-priority" : 1 }

Here the strategy does require context. 

```
// abbreviated type for example purposes
type TerminatingEndpoint struct {
	strategyOptions map[string]interface{}
}

func (e *TerminatingEndpoint) GetStrategyOptionsAsInt(strategyName string, defaultVal int) int {
	if e.strategyOptions == nil {
		return defaultVal
	}
	val, found := e.strategyOptions[strategyName]
	if !found {
		return defaultVal
	}
	iVal, ok := val.(int)
	if !ok {
		return defaultVal
	}
	return iVal
}

type PrioritySortedTerminatingEndpointList []*TerminatingEndpoint

func (p PrioritySortedTerminatingEndpointList) Len() int {
	return len(p)
}

func (p PrioritySortedTerminatingEndpointList) Less(i, j int) bool {
	p1 := p[i].GetStrategyOptionsAsInt("ha-priority", math.MaxInt32)
	p2 := p[i].GetStrategyOptionsAsInt("ha-priority", math.MaxInt32)
	return p1 < p2
}

func (p PrioritySortedTerminatingEndpointList) Swap(i, j int) {
	tmp := p[i]
	p[i] = p[j]
	p[j] = tmp
}

type HAPriorityStrategy struct {}

func (HAPriorityStrategy) GetEndpoint(_ *Service, _ string, endpoints[]*TerminatingEndpoint) *TerminatingEndpoint {
	sortable := PrioritySortedTerminatingEndpointList(endpoints)
	sort.Sort(sortable)
	return sortable[0]
}
```

**Questions**
Is map[string]interface{} overkill here? On the plus side it allows a binding to have separate options per strategy and allows any kind of data. On the downside it makes the data harder to work with (and crucially, less efficient) and we don't currently have any use cases that aren't covered by a simple number.

**Comment by michaelquigley** [comment]
I think this looks pretty solid. A few things that we might consider:

- Let's use `interface{}` instead of `map[string]interface{}`. That would flip the relationship around in the correct direction, letting the strategies define their own data model, and for cases where we're just using a simple "weight" or "priority" expressed as an `int`, we wouldn't have much cost in just asserting the `interface{}` to `int`.

- We should make sure we standardize the terminology. Let's use `terminatingRouter`, or `terminator` instead of `egressRouter`.

- I suspect we'll want to polish up the naming in general as this starts to flesh out. Some of the names are a little long, and feel a bit like Spring-style Java names (`PrioritySortedTerminatingEndpointList` for example).

But yes, this is looking good.

**Comment by plorenz** [comment]
@r-caamano Brought up another use case which I hadn't considered. He wondered how this would enable a single SDK client using multiple terminating routers for redundancy. 

I think from the fabric perspective, this should work fine as we can allow the SDK client to bind multiple times. The edge code and the SDK itself may need some facility to ensure that multiple binds reach multiple routers and that we don't bind more times than there are available routers.
